/**
 * @file hostile-metadata invalid workflow fixture manifest entries.
 *
 * This file is generated by tests/static-analysis/fixtures/refresh-metadata.ts.
 */

import { deepFreezeFixtureManifest } from "../../manifest-freeze";
import {
  diagnostic,
  type InvalidWorkflowFixtureSnapshot,
  invalidWorkflowFixture,
} from "../manifest-types";

export const HOSTILE_METADATA_FIXTURES = deepFreezeFixtureManifest([
  invalidWorkflowFixture({
    family: "hostile-metadata",
    fileName: "env-read-marker.js",
    sha256: "6c256fef53e618ceac2a49f352f9137ed90cd6fe4afbfff113f18952fa5ba383",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/meta-statically-unprovable",
        severity: "warning",
        message: "Workflow metadata must remain statically provable without evaluation.",
        span: {
          start: { offset: 72, line: 3, column: 16 },
          end: { offset: 256, line: 7, column: 7 },
        },
        spanText:
          '(() => {\n    globalThis.__odwLintHostileMetadataWasEvaluated =\n      process.env.ODW_LINT_HOSTILE_ENV_PROBE ?? "hostile-env-read-marker";\n    return "Hostile metadata fixture.";\n  })()',
      }),
    ],
  }),
  invalidWorkflowFixture({
    family: "hostile-metadata",
    fileName: "fs-write-marker.js",
    sha256: "adc803b39568cf8b62b42f3f8131b7c58539da4334b384621e7f758166de7bec",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/meta-statically-unprovable",
        severity: "warning",
        message: "Workflow metadata must remain statically provable without evaluation.",
        span: {
          start: { offset: 72, line: 3, column: 16 },
          end: { offset: 256, line: 9, column: 7 },
        },
        spanText:
          '(() => {\n    require("node:fs").writeFileSync(\n      process.env.ODW_LINT_HOSTILE_FS_MARKER_PATH,\n      "hostile-fs-write-marker",\n    );\n    return "Hostile metadata fixture.";\n  })()',
      }),
    ],
  }),
  invalidWorkflowFixture({
    family: "hostile-metadata",
    fileName: "global-marker.js",
    sha256: "af52ec3eea9c361ed0b5bd98263ea76e40a2bf202d5c35074962b1dddb0dcfa3",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/meta-statically-unprovable",
        severity: "warning",
        message: "Workflow metadata must remain statically provable without evaluation.",
        span: {
          start: { offset: 70, line: 3, column: 16 },
          end: { offset: 204, line: 6, column: 7 },
        },
        spanText:
          '(() => {\n    globalThis.__odwLintHostileMetadataWasEvaluated = "hostile-global-marker";\n    return "Hostile metadata fixture.";\n  })()',
      }),
    ],
  }),
  invalidWorkflowFixture({
    family: "hostile-metadata",
    fileName: "throw-marker.js",
    sha256: "859aa4e942c7db65de27f225232b9c244ad607da20fc07c913201e2d6074600d",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/meta-statically-unprovable",
        severity: "warning",
        message: "Workflow metadata must remain statically provable without evaluation.",
        span: {
          start: { offset: 69, line: 3, column: 16 },
          end: { offset: 144, line: 5, column: 7 },
        },
        spanText: '(() => {\n    throw new Error("ODW_LINT_HOSTILE_METADATA_EVALUATED");\n  })()',
      }),
    ],
  }),
]) satisfies readonly InvalidWorkflowFixtureSnapshot[];
