/**
 * @file Dual-compatibility workflow fixture manifest.
 *
 * This file is generated by tests/static-analysis/fixtures/refresh-metadata.ts.
 */
import {
  type DualCompatFixtureSnapshot,
  diagnostic,
  dualCompatFixture,
} from "./dual-compat/manifest-types";
import { deepFreezeFixtureManifest } from "./manifest-freeze";

export type {
  DualCompatFixtureDiagnostic,
  DualCompatFixtureFamily,
  DualCompatFixtureSnapshot,
  DualCompatFixtureStatus,
} from "./dual-compat/manifest-types";

export const DUAL_COMPAT_FIXTURE_SNAPSHOTS = deepFreezeFixtureManifest([
  dualCompatFixture({
    family: "pure-metadata",
    fileName: "simple-agent.js",
    sha256: "72ce1ee32ddc638b3bcff9282b1b0ac9ef7bcc9f2e8f26b57db96d9da762e1c2",
    expectedStatus: "no-error",
    expectedDiagnostics: [],
  }),
  dualCompatFixture({
    family: "pure-metadata",
    fileName: "string-decoy.js",
    sha256: "2c710fe0430341b56a7c866189a179dff7c7b0de9d8e547d3d8e480f0ad7a3b3",
    expectedStatus: "no-error",
    expectedDiagnostics: [],
  }),
  dualCompatFixture({
    family: "claude-pure-meta",
    fileName: "closed-constant-retries.js",
    sha256: "092db658e90944197aa9cfb35defadba4bc3bb489b9bc17322a7434580b0d973",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/claude-pure-meta",
        severity: "warning",
        message:
          "Workflow metadata is not a pure literal, which Claude Code rejects because its static workflow reader cannot evaluate computed metadata.",
        span: {
          start: { offset: 249, line: 8, column: 12 },
          end: { offset: 254, line: 8, column: 17 },
        },
        spanText: "1 - 2",
      }),
    ],
  }),
  dualCompatFixture({
    family: "claude-pure-meta",
    fileName: "concat-tag.js",
    sha256: "aefddfafb92fff53c096a6158146905b14b7ab2935dfdefcbdd41c2c6f51d08e",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/claude-pure-meta",
        severity: "warning",
        message:
          "Workflow metadata is not a pure literal, which Claude Code rejects because its static workflow reader cannot evaluate computed metadata.",
        span: {
          start: { offset: 235, line: 8, column: 10 },
          end: { offset: 244, line: 8, column: 19 },
        },
        spanText: '"a" + "b"',
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "date-alias.js",
    sha256: "00f0b6ee316a10c873c3c242504290cb33fdf642525dd6f763826aeab4133481",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/no-date-now",
        severity: "warning",
        message:
          "Workflow calls Date.now(), which Claude Code rejects because it breaks deterministic run resumption.",
        span: {
          start: { offset: 263, line: 11, column: 19 },
          end: { offset: 276, line: 11, column: 32 },
        },
        spanText: "ClockDate.now",
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "date-now.js",
    sha256: "5388a5c09bcb1e4dea2ca481bd62f4a1930501d6ca5711e100872d514253905b",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/no-date-now",
        severity: "warning",
        message:
          "Workflow calls Date.now(), which Claude Code rejects because it breaks deterministic run resumption.",
        span: {
          start: { offset: 235, line: 10, column: 19 },
          end: { offset: 243, line: 10, column: 27 },
        },
        spanText: "Date.now",
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "date-now-computed.js",
    sha256: "af0379372daf10e1d9c414c79c2492dab18d1bffd2b29e2844231a46eacdd985",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/no-date-now",
        severity: "warning",
        message:
          "Workflow calls Date.now(), which Claude Code rejects because it breaks deterministic run resumption.",
        span: {
          start: { offset: 331, line: 11, column: 19 },
          end: { offset: 342, line: 11, column: 30 },
        },
        spanText: 'Date["now"]',
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "global-date-now.js",
    sha256: "a7e8062190c9799170dcb1e4ef86b62bc53e650c63106354ab96433d950f83a1",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/no-date-now",
        severity: "warning",
        message:
          "Workflow calls Date.now(), which Claude Code rejects because it breaks deterministic run resumption.",
        span: {
          start: { offset: 243, line: 10, column: 19 },
          end: { offset: 262, line: 10, column: 38 },
        },
        spanText: "globalThis.Date.now",
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "math-random.js",
    sha256: "fd02d009c5d874894a1c01f25dfcd9927c98d18218c84a4062a01f88fd8aa330",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/no-math-random",
        severity: "warning",
        message:
          "Workflow calls Math.random(), which Claude Code rejects because it breaks deterministic run resumption.",
        span: {
          start: { offset: 239, line: 10, column: 16 },
          end: { offset: 250, line: 10, column: 27 },
        },
        spanText: "Math.random",
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "new-date.js",
    sha256: "6f986c3c0c27d7320a25d31d5625439c71ef0b4a10391895e04386b159a91ff4",
    expectedStatus: "warning",
    expectedDiagnostics: [
      diagnostic({
        rule: "odw/no-argless-new-date",
        severity: "warning",
        message:
          "Workflow constructs new Date() without arguments, which Claude Code rejects because it breaks deterministic run resumption.",
        span: {
          start: { offset: 247, line: 10, column: 17 },
          end: { offset: 257, line: 10, column: 27 },
        },
        spanText: "new Date()",
      }),
    ],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "shadowed-date.js",
    sha256: "ab6f24acd8ff8daf38b94f47cfe02a0e86d8662008d2032323164c26e7c486a6",
    expectedStatus: "no-error",
    expectedDiagnostics: [],
  }),
  dualCompatFixture({
    family: "deterministic-time",
    fileName: "masked-text.js",
    sha256: "926691a3f1534e8dc9321bb3572bf0dce6ddb0ed83e63a3146fcce887c63a260",
    expectedStatus: "no-error",
    expectedDiagnostics: [],
  }),
]) satisfies readonly DualCompatFixtureSnapshot[];
